name: Push Flyers to BigQuery

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * *"    

jobs:
  scrape:
    runs-on: windows-latest
    steps:
    
    - name: Checking out repo
      uses: actions/checkout@v3
      
    - name: Setting up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11.7"
        
    - name: Installing packages
      run: |
        pip install selenium==4.18.1 beautifulsoup4 pyvirtualdisplay pandas duckdb fuckit pyarrow google-cloud-bigquery google-auth
        
    - name: Running Python script
      env:  
          BIGQUERY_KEYS_JSON: ${{ secrets.BIGQUERY_KEYS_JSON }}
      run: python "Scrape Flyers to BigQuery.py"
